import { StudioMotion } from "./studio-motion";
import Link from "next/link";
import projects from "./projects.json";
import { ProjectPreview } from "./project-evidence";
import { ProjectLinks } from "./project-links";

export function StudioHome() {
  return <div className="studio-home"><StudioMotion /><a className="page-skip" href="#studio-content">Skip to content</a>
    <header className="studio-nav"><Link className="studio-signature" href="/">humberto<span> / software engineer</span></Link><nav aria-label="Studio navigation"><Link href="#studio-work">Work</Link><Link href="/about">About</Link><Link href="/writing">Writing</Link><Link href="#contact">Let’s talk ↗</Link></nav></header>
    <section className="studio-hero" id="studio-content" tabIndex={-1}><div className="studio-kicker"><span className="studio-dot" /> BASED IN UTAH · BUILDING AT kW ENGINEERING</div><div className="studio-orbit" aria-hidden="true"><div className="orbit-ring ring-one" /><div className="orbit-ring ring-two" /><div className="orbit-ring ring-three" /><div className="orbit-core" /><span className="orbit-coordinate">SYSTEM / HV.2026</span></div><h1>Humberto<br />Villanueva<span className="studio-period">.</span></h1><div className="studio-hero-bottom"><p>Ideas into interfaces.<br className="studio-desktop-break" /> Code into things people use.</p><div><span>Web applications. AI integrations. Reliable data.</span><Link href="#studio-work">Explore the work <span aria-hidden="true">↓</span></Link></div></div><div className="studio-index" aria-hidden="true">ENGINEERING / PRODUCT / AI</div></section>
    <section className="studio-employer" aria-labelledby="studio-current"><span className="studio-label">01 / CURRENT WORK</span><div><h2 id="studio-current">Specta <span>at kW Engineering</span></h2><p>I contribute to AI integrations, document processing, data reliability, and interfaces for building operators.</p></div><Link href="/experience">My role ↗</Link></section>
    <section id="studio-work" className="studio-work"><div className="studio-section-heading"><div><span className="studio-label">02 / SELECTED PROJECTS</span><h2>From idea to<br />working software.</h2></div><Link href="/projects">All projects ↗</Link></div><div className="studio-projects">{projects.filter(project=>project.repo).map((project,index)=><article className="studio-project" key={project.repo}><div className="studio-project-top"><span>0{index+1}</span><span>{project.type}</span></div><ProjectPreview repo={project.repo} /><div className="studio-project-copy"><h3>{project.title}</h3><p>{project.text}</p><ProjectLinks repo={project.repo} /></div></article>)}</div></section>
    <section className="studio-person"><div><span className="studio-label">03 / BEHIND THE WORK</span><h2>Curious by nature.<br />Engineer by practice.</h2><p>I like finding the reason something broke, working through a fix, and making sure it holds up. Away from the screen, it’s family and football.</p><div className="studio-person-links"><Link href="/about">More about me ↗</Link><Link href="/writing">Engineering notes ↗</Link></div></div></section>
  </div>;
}
